package handler

var CountryAliases = map[string]string{
	"usa":         "united states",
	"uk":          "united kingdom",
	"drc":         "dr congo",
	"ivory coast": "côte d'ivoire",
}

var CountryCodes = map[string]string{
	"nigeria":                  "NG",
	"tanzania":                 "TZ",
	"uganda":                   "UG",
	"sudan":                    "SD",
	"united states":            "US",
	"madagascar":               "MG",
	"united kingdom":           "GB",
	"india":                    "IN",
	"cameroon":                 "CM",
	"cape verde":               "CV",
	"republic of the congo":    "CG",
	"mozambique":               "MZ",
	"south africa":             "ZA",
	"mali":                     "ML",
	"angola":                   "AO",
	"dr congo":                 "CD",
	"france":                   "FR",
	"kenya":                    "KE",
	"zambia":                   "ZM",
	"eritrea":                  "ER",
	"gabon":                    "GA",
	"rwanda":                   "RW",
	"senegal":                  "SN",
	"namibia":                  "NA",
	"gambia":                   "GM",
	"côte d'ivoire":            "CI",
	"ethiopia":                 "ET",
	"morocco":                  "MA",
	"malawi":                   "MW",
	"brazil":                   "BR",
	"tunisia":                  "TN",
	"somalia":                  "SO",
	"ghana":                    "GH",
	"zimbabwe":                 "ZW",
	"egypt":                    "EG",
	"benin":                    "BJ",
	"western sahara":           "EH",
	"australia":                "AU",
	"china":                    "CN",
	"botswana":                 "BW",
	"canada":                   "CA",
	"liberia":                  "LR",
	"mauritania":               "MR",
	"burkina faso":             "BF",
	"central african republic": "CF",
	"mauritius":                "MU",
	"algeria":                  "DZ",
	"burundi":                  "BI",
	"guinea-bissau":            "GW",
	"eswatini":                 "SZ",
	"sierra leone":             "SL",
	"comoros":                  "KM",
	"seychelles":               "SC",
	"japan":                    "JP",
}
